Algoritmo "par 1 a 100"
// Disciplina   : CAP
// Professor   : Joice
// Descrição   : Par de 1 a 100
// Autor(a)    : Juliano Vitorino da Silva
// Data atual  : 17/04/2024
Var
// Seção de Declarações das variáveis 
   i: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 2 ate 100 passo 2 faca
        escreva (i)
   fimpara

Fimalgoritmo
